# Generated by Django 5.1.2 on 2024-10-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0002_alter_quote_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
